# Generated by Django 4.2.6 on 2023-12-01 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_guest_alter_reservation_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='checkedIn',
            field=models.BooleanField(default=False),
        ),
    ]
