# Generated by Django 4.2.6 on 2023-12-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_checkedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='isCurrent',
            field=models.BooleanField(default=True),
        ),
    ]
