# Generated by Django 4.2 on 2024-04-03 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_alter_reservation_iscurrent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrival',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='departure',
            field=models.DateTimeField(),
        ),
    ]
