# Generated by Django 4.2 on 2024-04-14 23:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0003_remove_rental_isoccupied'),
        ('reservations', '0006_reservation_iscancelled'),
    ]

    operations = [
        migrations.CreateModel(
            name='disabledDates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to='rentals.rental')),
            ],
        ),
    ]
