# Generated by Django 4.2.6 on 2023-11-29 09:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RoomPictures',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='rental_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isOccupied', models.BooleanField(default=False)),
                ('profilePic', models.ImageField(blank=True, null=True, upload_to='rental_pics')),
                ('roomPics', models.ManyToManyField(blank=True, to='rentals.roompictures')),
            ],
        ),
    ]
