# Generated by Django 4.2 on 2024-04-14 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_remove_rental_roompics_rental_roompicfive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='isOccupied',
        ),
    ]
